name: Deploy Web App

on:
  push:
    paths:
      - 'apps/web/**'
      - 'packages/**'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        working-directory: apps/web
        run: npm run build

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Log in to Google Container Registry
        run: echo ${{ secrets.GCP_SA_KEY }} | docker login -u _json_key --password-stdin https://gcr.io

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/web
          push: true
          tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/web:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy web-service \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/web:latest \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated
